services:
  # Socket.IO 实时通信服务
  socketio:
    image: node:18-alpine
    container_name: cici-socketio
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=cici-redis
      - REDIS_PORT=6379
    working_dir: /app
    volumes:
      - ./app-services/socketio:/app
    command: sh -c "npm install && node server.js"
    networks:
      - cici-network
    restart: unless-stopped

  # 文件处理服务
  fileservice:
    image: node:18-alpine
    container_name: cici-fileservice
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    working_dir: /app
    volumes:
      - ./app-services/fileservice:/app
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    command: sh -c "npm install && node server.js"
    networks:
      - cici-network
    restart: unless-stopped

  # 缓存管理服务
  cacheservice:
    image: node:18-alpine
    container_name: cici-cacheservice
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=cici-redis
      - REDIS_PORT=6379
    working_dir: /app
    volumes:
      - ./app-services/cacheservice:/app
    command: sh -c "npm install && node server.js"
    networks:
      - cici-network
    restart: unless-stopped

  # API网关服务
  apigateway:
    image: node:18-alpine
    container_name: cici-apigateway
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
    working_dir: /app
    volumes:
      - ./app-services/apigateway:/app
    command: sh -c "npm install && node server.js"
    networks:
      - cici-network
    restart: unless-stopped

networks:
  cici-network:
    external: true
    name: server_cici-network
