/**
 * 错误码定义
 * 统一的错误码管理，便于前后端错误处理
 */

export const ERROR_CODES = {
  // 通用错误 (1000-1999)
  UNKNOWN_ERROR: 1000,
  INVALID_PARAMETERS: 1001,
  NETWORK_ERROR: 1002,
  TIMEOUT_ERROR: 1003,
  SERVER_ERROR: 1004,

  // 认证错误 (2000-2999)
  UNAUTHORIZED: 2000,
  INVALID_TOKEN: 2001,
  TOKEN_EXPIRED: 2002,
  INVALID_CREDENTIALS: 2003,
  ACCOUNT_LOCKED: 2004,
  ACCOUNT_NOT_VERIFIED: 2005,
  PASSWORD_TOO_WEAK: 2006,
  EMAIL_ALREADY_EXISTS: 2007,
  PHONE_ALREADY_EXISTS: 2008,

  // 用户错误 (3000-3999)
  USER_NOT_FOUND: 3000,
  USER_ALREADY_EXISTS: 3001,
  INSUFFICIENT_PERMISSIONS: 3002,
  PROFILE_INCOMPLETE: 3003,
  FOLLOW_SELF_ERROR: 3004,
  ALREADY_FOLLOWING: 3005,
  NOT_FOLLOWING: 3006,

  // 内容错误 (4000-4999)
  POST_NOT_FOUND: 4000,
  POST_ALREADY_LIKED: 4001,
  POST_NOT_LIKED: 4002,
  CONTENT_TOO_LONG: 4003,
  INAPPROPRIATE_CONTENT: 4004,
  DUPLICATE_CONTENT: 4005,

  // 活动错误 (5000-5999)
  ACTIVITY_NOT_FOUND: 5000,
  ACTIVITY_FULL: 5001,
  ACTIVITY_EXPIRED: 5002,
  ACTIVITY_NOT_STARTED: 5003,
  ALREADY_JOINED: 5004,
  NOT_JOINED: 5005,
  CANNOT_LEAVE_OWN_ACTIVITY: 5006,

  // 门票错误 (6000-6999)
  TICKET_NOT_FOUND: 6000,
  TICKET_SOLD_OUT: 6001,
  TICKET_EXPIRED: 6002,
  TICKET_ALREADY_USED: 6003,
  INVALID_TICKET_TYPE: 6004,
  REFUND_NOT_ALLOWED: 6005,

  // 支付错误 (7000-7999)
  PAYMENT_FAILED: 7000,
  INSUFFICIENT_FUNDS: 7001,
  PAYMENT_METHOD_INVALID: 7002,
  REFUND_FAILED: 7003,
  ORDER_NOT_FOUND: 7004,
  ORDER_ALREADY_PAID: 7005,
  ORDER_CANCELLED: 7006,

  // 文件上传错误 (8000-8999)
  FILE_TOO_LARGE: 8000,
  INVALID_FILE_TYPE: 8001,
  UPLOAD_FAILED: 8002,
  FILE_NOT_FOUND: 8003,
  STORAGE_LIMIT_EXCEEDED: 8004,

  // 聊天错误 (9000-9999)
  CHAT_NOT_FOUND: 9000,
  MESSAGE_TOO_LONG: 9001,
  BLOCKED_USER: 9002,
  GROUP_FULL: 9003,
  NOT_GROUP_MEMBER: 9004,
  INSUFFICIENT_GROUP_PERMISSIONS: 9005
}

// 错误信息映射
export const ERROR_MESSAGES = {
  [ERROR_CODES.UNKNOWN_ERROR]: '未知错误，请稍后重试',
  [ERROR_CODES.INVALID_PARAMETERS]: '参数错误',
  [ERROR_CODES.NETWORK_ERROR]: '网络连接失败，请检查网络设置',
  [ERROR_CODES.TIMEOUT_ERROR]: '请求超时，请稍后重试',
  [ERROR_CODES.SERVER_ERROR]: '服务器内部错误',

  [ERROR_CODES.UNAUTHORIZED]: '未授权访问',
  [ERROR_CODES.INVALID_TOKEN]: '无效的访问令牌',
  [ERROR_CODES.TOKEN_EXPIRED]: '访问令牌已过期，请重新登录',
  [ERROR_CODES.INVALID_CREDENTIALS]: '用户名或密码错误',
  [ERROR_CODES.ACCOUNT_LOCKED]: '账户已被锁定',
  [ERROR_CODES.ACCOUNT_NOT_VERIFIED]: '账户未验证，请先验证邮箱',
  [ERROR_CODES.PASSWORD_TOO_WEAK]: '密码强度不够',
  [ERROR_CODES.EMAIL_ALREADY_EXISTS]: '邮箱已被注册',
  [ERROR_CODES.PHONE_ALREADY_EXISTS]: '手机号已被注册',

  [ERROR_CODES.USER_NOT_FOUND]: '用户不存在',
  [ERROR_CODES.USER_ALREADY_EXISTS]: '用户已存在',
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: '权限不足',
  [ERROR_CODES.PROFILE_INCOMPLETE]: '个人资料不完整',
  [ERROR_CODES.FOLLOW_SELF_ERROR]: '不能关注自己',
  [ERROR_CODES.ALREADY_FOLLOWING]: '已经关注了该用户',
  [ERROR_CODES.NOT_FOLLOWING]: '未关注该用户',

  [ERROR_CODES.POST_NOT_FOUND]: '内容不存在',
  [ERROR_CODES.POST_ALREADY_LIKED]: '已经点赞过了',
  [ERROR_CODES.POST_NOT_LIKED]: '还未点赞',
  [ERROR_CODES.CONTENT_TOO_LONG]: '内容过长',
  [ERROR_CODES.INAPPROPRIATE_CONTENT]: '内容违规',
  [ERROR_CODES.DUPLICATE_CONTENT]: '重复内容',

  [ERROR_CODES.ACTIVITY_NOT_FOUND]: '活动不存在',
  [ERROR_CODES.ACTIVITY_FULL]: '活动人数已满',
  [ERROR_CODES.ACTIVITY_EXPIRED]: '活动已结束',
  [ERROR_CODES.ACTIVITY_NOT_STARTED]: '活动还未开始',
  [ERROR_CODES.ALREADY_JOINED]: '已经参加了该活动',
  [ERROR_CODES.NOT_JOINED]: '未参加该活动',
  [ERROR_CODES.CANNOT_LEAVE_OWN_ACTIVITY]: '不能退出自己创建的活动',

  [ERROR_CODES.TICKET_NOT_FOUND]: '门票不存在',
  [ERROR_CODES.TICKET_SOLD_OUT]: '门票已售完',
  [ERROR_CODES.TICKET_EXPIRED]: '门票已过期',
  [ERROR_CODES.TICKET_ALREADY_USED]: '门票已使用',
  [ERROR_CODES.INVALID_TICKET_TYPE]: '无效的门票类型',
  [ERROR_CODES.REFUND_NOT_ALLOWED]: '不支持退款',

  [ERROR_CODES.PAYMENT_FAILED]: '支付失败',
  [ERROR_CODES.INSUFFICIENT_FUNDS]: '余额不足',
  [ERROR_CODES.PAYMENT_METHOD_INVALID]: '支付方式无效',
  [ERROR_CODES.REFUND_FAILED]: '退款失败',
  [ERROR_CODES.ORDER_NOT_FOUND]: '订单不存在',
  [ERROR_CODES.ORDER_ALREADY_PAID]: '订单已支付',
  [ERROR_CODES.ORDER_CANCELLED]: '订单已取消',

  [ERROR_CODES.FILE_TOO_LARGE]: '文件过大',
  [ERROR_CODES.INVALID_FILE_TYPE]: '不支持的文件类型',
  [ERROR_CODES.UPLOAD_FAILED]: '文件上传失败',
  [ERROR_CODES.FILE_NOT_FOUND]: '文件不存在',
  [ERROR_CODES.STORAGE_LIMIT_EXCEEDED]: '存储空间不足',

  [ERROR_CODES.CHAT_NOT_FOUND]: '聊天不存在',
  [ERROR_CODES.MESSAGE_TOO_LONG]: '消息过长',
  [ERROR_CODES.BLOCKED_USER]: '用户已被屏蔽',
  [ERROR_CODES.GROUP_FULL]: '群组人数已满',
  [ERROR_CODES.NOT_GROUP_MEMBER]: '不是群组成员',
  [ERROR_CODES.INSUFFICIENT_GROUP_PERMISSIONS]: '群组权限不足'
}

/**
 * 获取错误信息
 * @param {number} errorCode - 错误码
 * @returns {string} 错误信息
 */
export function getErrorMessage(errorCode) {
  return ERROR_MESSAGES[errorCode] || ERROR_MESSAGES[ERROR_CODES.UNKNOWN_ERROR]
}

/**
 * 创建标准错误对象
 * @param {number} code - 错误码
 * @param {string} [message] - 自定义错误信息
 * @param {any} [data] - 额外数据
 * @returns {object} 标准错误对象
 */
export function createError(code, message, data) {
  return {
    code,
    message: message || getErrorMessage(code),
    data,
    timestamp: new Date().toISOString()
  }
}

export default {
  ERROR_CODES,
  ERROR_MESSAGES,
  getErrorMessage,
  createError
}
